jobs:
    - job: job1
    - job: job2
      cancelTimeoutInMinutes: 5
      pool: server
      steps:
          - task: Bash@3
    - job: job3
      cancelTimeoutInMinutes: $[ variables.theCancelTimeoutInMinutes ]
      pool: server
      steps:
          - task: Bash@3
