resources:
    containers:
        - container: dev1
          image: ubuntu:16.04
          type: docker
jobs:
    - job: job1
    - job: job2
      container: dev1
    - job: job3
      pool: myPool
      container: $[ variables.container ]
      steps:
          - script: echo hi
