jobs:
    - job: job1
    - job: job2
      pool: pool2
    - job: job3
      pool: pool3
    - job: job4
      pool:
          name: pool4
          demands: one -eq one
    - job: job5
      pool:
          name: pool5
          demands: abc -eq one
    - job: job6
      pool:
          name: pool6
          demands:
              - demand1 -equals value1
              - demand2 -equals value2
    - job: job7
      pool:
          demands:
              - demand1 -equals value1
              - demand2 -equals value2
