jobs:
    - job: job1
    - job: job2
      strategy:
          matrix:
              x64_release:
                  arch: x64
                  config: release
              x86_debug:
                  arch: x86
                  config: debug
      pool: server
    - job: job3
      strategy:
          matrix:
              x64_release:
                  arch: x64
                  config: release
              x86_debug:
                  arch: x86
                  config: debug
          maxParallel: 2
      pool: server
    - job: job4
      strategy:
          matrix: $[ variables.matrix ]
          maxParallel: $[ variables.maxParallel ]
      pool: server
      steps:
          - task: Bash@3
