jobs:
- job: job1
- job: job2
  timeoutInMinutes: 5
  pool: server
  steps:
  - task: Bash@3
- job: job3
  timeoutInMinutes: $[ variables.theTimeoutInMinutes ]
  pool: server
  steps:
  - task: Bash@3