jobs:
- job: job1
- job: job2
  variables:
    variableOne: value1
    variableTwo: value2
- job: job3
  variables:
    - name: variableOne
      value: value1
    - name: variableTwo
      value: value2
- job: job4
  variables:
    - name: variableOne
      value: value1
    - group: myVariableGroup
    - name: variableTwo
      value: value2